apiVersion: v1
kind: LimitRange
metadata:
  name: myapp-pod
spec:
  limits:
  - default:
      memory: 1Gi
    defaultRequest:
      memory: 1Gi
    max:
      memory: 1Gi
    min:
      memory: 500mi
    type: Container
