apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  # namespace: dev
  labels:
    name: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations: # podにトレランスを追加する場合　　　　　　ノードを汚染し、汚染したノードに配置できるようにするためトレランスする
  - key: "app" # これら全てダブルコートで囲まなければならない
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule" # スケジュールはなし
